---
- name: Install Ngnix
  dnf:
    name: nginx
    state: present

- name: start and enable ngnix
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy Nginx configuration
  template:
    src: wordpress.conf.j2
    dest: /etc/nginx/conf.d/wordpress.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx
