---
- name: configure wordpress server
  hosts: web
  become: yes

  vars_files:
  - ../group_vars/all.yml
  - ../group_vars/vault.yml

  roles:
    - user
    - ssl
    - nginx
    - php
    - mysql
    - wordpress
    - phpmyadmin

